language: node_js
sudo: false
dist: trusty

node_js:
  - node

cache:
  yarn: true
  directories:
    - "node_modules"

script:
  - yarn compile
  - yarn lint
  - yarn test
  - yarn benchmark

deploy:
  skip_cleanup: true
  provider: npm
  email: $NPM_EMAIL_ADDRESS
  api_key: $NPM_AUTH_TOKEN

  on:
    branch: master
